apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-microservice-deployment
  labels:
    app: python-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-microservice
  template:
    metadata:
      labels:
        app: python-microservice
    spec:
      containers:
        - name: python-microservice
          image: realestate1234/python-microservice:latest # Replace with your Docker Hub image
          ports:
            - containerPort: 5000 # Ensure this matches the application port
          env:
            - name: ENV_VAR_NAME
              value: "value" # Replace with actual environment variables if required
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: python-microservice-svc
spec:
  type: ClusterIP
  selector:
    app: python-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
